In [243]:
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [244]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [245]:
sum(df.duplicated())

0

In [246]:
df.isna().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [247]:
df.shape

(569, 33)

In [248]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [249]:
df.drop(['id', 'Unnamed: 32'], axis=1, inplace=True)

In [250]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [251]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2, random_state=0)

In [252]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((455, 30), (455,), (114, 30), (114,))

In [253]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [254]:
y_train 

338    B
427    B
406    B
96     B
490    B
      ..
277    M
9      M
359    B
192    B
559    B
Name: diagnosis, Length: 455, dtype: object

In [255]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [256]:
y_train 

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,

In [257]:
## transform the numpy arrays to tensor 

X_train_tensor = torch.from_numpy(X_train)
y_train_tensor = torch.from_numpy(y_train)
X_test_tensor = torch.from_numpy(X_test)
y_test_tensor = torch.from_numpy(y_test)

In [258]:
X_train_tensor.shape, y_train_tensor.shape, X_test_tensor.shape, y_test_tensor.shape

(torch.Size([455, 30]),
 torch.Size([455]),
 torch.Size([114, 30]),
 torch.Size([114]))

In [259]:
## Model Building 

class BreastCancerModel:
    
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True) # 30 * 1
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)
        
    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_hat = torch.sigmoid(z)
        return y_hat
    
    def loss_function(self, y_hat, y):
        epsilon = 1e-7
        y_hat = torch.clamp(y_hat, epsilon, 1 - epsilon)
        bce_loss = -(y * torch.log(y_hat) + (1 - y) * torch.log(1 - y_hat)).mean()
        return bce_loss

In [260]:
## Parameters 

lr = 0.1
epochs = 100

In [261]:
## Training Pipeline 

model = BreastCancerModel(X_train_tensor)

for epoch in range(epochs):
    # forward pass  
    y_pred = model.forward(X_train_tensor)
    # print(y_pred)
    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)
    # backward pass
    loss.backward()
    # parameters update
    with torch.no_grad():
        model.weights -= lr * model.weights.grad
        model.bias -= lr * model.bias.grad
    # zero gradient 
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    # Print loss in each epoch 
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 3.889768409220055
Epoch: 2, Loss: 3.7826844930033756
Epoch: 3, Loss: 3.6724781030640217
Epoch: 4, Loss: 3.5603863983643422
Epoch: 5, Loss: 3.445394639029251
Epoch: 6, Loss: 3.323986962235086
Epoch: 7, Loss: 3.194336863855367
Epoch: 8, Loss: 3.0614530130929696
Epoch: 9, Loss: 2.9262952134788667
Epoch: 10, Loss: 2.7826944141989878
Epoch: 11, Loss: 2.635859302845917
Epoch: 12, Loss: 2.482036434001178
Epoch: 13, Loss: 2.322535360526163
Epoch: 14, Loss: 2.1580512474882547
Epoch: 15, Loss: 1.9982557825661202
Epoch: 16, Loss: 1.841157956344946
Epoch: 17, Loss: 1.6896237070843978
Epoch: 18, Loss: 1.5392143991475011
Epoch: 19, Loss: 1.3928001033212527
Epoch: 20, Loss: 1.2601216648980003
Epoch: 21, Loss: 1.1433456484735953
Epoch: 22, Loss: 1.0441592619336502
Epoch: 23, Loss: 0.9632993308436077
Epoch: 24, Loss: 0.9001881943692343
Epoch: 25, Loss: 0.8528765572727383
Epoch: 26, Loss: 0.818415445338202
Epoch: 27, Loss: 0.7935514735106439
Epoch: 28, Loss: 0.7753919389328632
Epoch: 29,

In [262]:
# model evaluation 

with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > .5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
print("Accuracy: {:.2f}%".format((accuracy.item()) * 100))

Accuracy: 58.31%


In [263]:
## with nn module 

import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [264]:
class NNModel(nn.Module):
    
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1) # linear layer, only one neuron 
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, inp_features):
        out = self.linear(inp_features) # z = wx + b
        out = self.sigmoid(out) # activation function 
        return out 

In [265]:
features = torch.rand(10, 5)

In [266]:
model = NNModel(features.shape[1])

In [267]:
# model.forward(features) dont use this, do this instead 

model(features) # this will trigger model.forward()

tensor([[0.4877],
        [0.4964],
        [0.4486],
        [0.4679],
        [0.4649],
        [0.4203],
        [0.4219],
        [0.4568],
        [0.4495],
        [0.4949]], grad_fn=<SigmoidBackward0>)

In [268]:
model.linear.weight

Parameter containing:
tensor([[ 0.0808, -0.1867, -0.2735,  0.0196, -0.0729]], requires_grad=True)

In [269]:
model.linear.bias

Parameter containing:
tensor([0.0867], requires_grad=True)

In [270]:
from torchinfo import summary

summary(model, (10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
NNModel                                  [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [271]:
features.shape

torch.Size([10, 5])

In [272]:
# create a neural network with hidden weights, use relu and sigmoid

class NNModel(nn.Module):
    
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3) # linear layer, only one neuron
        self.relu = nn.ReLU() # hidden layer 
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, inp_features):
        out = self.linear1(inp_features) # z = wx + b
        out = self.relu(out) # relu activation 
        out = self.linear2(out) # final layer 
        out = self.sigmoid(out) # activation function 
        return out 


In [273]:
model1 = NNModel(features.shape[1])

In [274]:
model1.linear1.weight

Parameter containing:
tensor([[-0.1278,  0.4470,  0.3299, -0.3788, -0.2063],
        [ 0.1642, -0.0280, -0.3216, -0.0878, -0.0084],
        [ 0.3977, -0.2818,  0.3140, -0.3685, -0.0513]], requires_grad=True)

In [275]:
model1.linear2.weight

Parameter containing:
tensor([[ 0.4300, -0.3872,  0.2748]], requires_grad=True)

In [276]:
summary(model1, (10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
NNModel                                  [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [277]:
class NNModel1(nn.Module):
    
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3), # linear layer, only one neuron
            nn.ReLU(), # hidden layer 
            nn.Linear(3, 1),
            nn.Sigmoid(),
        )
    
    def forward(self, inp_features):
        out = self.network(inp_features)
        return out

In [278]:
model2 = NNModel1(features.shape[1])

In [279]:
model2(features)

tensor([[0.3947],
        [0.3959],
        [0.3955],
        [0.3951],
        [0.3965],
        [0.3974],
        [0.3956],
        [0.3952],
        [0.3964],
        [0.3942]], grad_fn=<SigmoidBackward0>)

In [280]:
## Model Building 

class BreastCancerModel1(nn.Module):
    
    def __init__(self, inp_features):
        super().__init__()
        self.linear = nn.Linear(inp_features, 1, dtype=torch.float64)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [281]:
X_train_tensor.shape

torch.Size([455, 30])

In [282]:
X_train_tensor.shape, X_test_tensor.shape, y_test_tensor.shape, y_train_tensor.shape

(torch.Size([455, 30]),
 torch.Size([114, 30]),
 torch.Size([114]),
 torch.Size([455]))

In [283]:
loss_function = nn.BCELoss()

In [284]:
## Training Pipeline 
epochs = 25
model = BreastCancerModel1(X_train_tensor.shape[1])

for epoch in range(epochs):
    # forward pass  
    y_pred = model(X_train_tensor)
    # print(y_pred)
    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1).type(torch.float64))
    # backward pass
    loss.backward()
    # parameters update
    with torch.no_grad():
        model.linear.weight -= lr * model.linear.weight.grad
        model.linear.bias -= lr * model.linear.bias.grad
    # zero gradient 
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()
    # Print loss in each epoch 
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.7776857766595693
Epoch: 2, Loss: 0.5552899340054914
Epoch: 3, Loss: 0.44277997897948623
Epoch: 4, Loss: 0.3782306175813678
Epoch: 5, Loss: 0.33633047520481496
Epoch: 6, Loss: 0.3066879522470343
Epoch: 7, Loss: 0.284413864502619
Epoch: 8, Loss: 0.26692715536612394
Epoch: 9, Loss: 0.2527390886131039
Epoch: 10, Loss: 0.24093007485655313
Epoch: 11, Loss: 0.230900474232197
Epoch: 12, Loss: 0.2222417822644745
Epoch: 13, Loss: 0.21466547983137008
Epoch: 14, Loss: 0.20796153209404195
Epoch: 15, Loss: 0.20197305428366716
Epoch: 16, Loss: 0.196580238824439
Epoch: 17, Loss: 0.1916898154045217
Epoch: 18, Loss: 0.1872279382212348
Epoch: 19, Loss: 0.18313526385716034
Epoch: 20, Loss: 0.17936346858165161
Epoch: 21, Loss: 0.17587273486803384
Epoch: 22, Loss: 0.17262990489479393
Epoch: 23, Loss: 0.16960710211319896
Epoch: 24, Loss: 0.1667806871451338
Epoch: 25, Loss: 0.16413045635139992


In [285]:
## Training Pipeline 
## Remove optimization and use torch.optim 
epochs = 25
lr = .5
model = BreastCancerModel1(X_train_tensor.shape[1])
optimizer = optim.SGD(model.parameters(), lr=lr)

for epoch in range(epochs):
    # forward pass  
    y_pred = model(X_train_tensor)
    # print(y_pred)
    # loss calculate
    loss = loss_function(y_pred, y_train_tensor.view(-1, 1).type(torch.float64))
    # backward pass
    loss.backward()
    # clear gradients 
    optimizer.zero_grad()
    # parameters update
    '''
    with torch.no_grad():
        model.linear.weight -= lr * model.linear.weight.grad
        model.linear.bias -= lr * model.linear.bias.grad
    '''
    optimizer.step()
    # zero gradient 
    '''
    model.linear.weight.grad.zero_()
    model.linear.bias.grad.zero_()
    '''
    # Print loss in each epoch 
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 0.7095834044141647
Epoch: 2, Loss: 0.7095834044141647
Epoch: 3, Loss: 0.7095834044141647
Epoch: 4, Loss: 0.7095834044141647
Epoch: 5, Loss: 0.7095834044141647
Epoch: 6, Loss: 0.7095834044141647
Epoch: 7, Loss: 0.7095834044141647
Epoch: 8, Loss: 0.7095834044141647
Epoch: 9, Loss: 0.7095834044141647
Epoch: 10, Loss: 0.7095834044141647
Epoch: 11, Loss: 0.7095834044141647
Epoch: 12, Loss: 0.7095834044141647
Epoch: 13, Loss: 0.7095834044141647
Epoch: 14, Loss: 0.7095834044141647
Epoch: 15, Loss: 0.7095834044141647
Epoch: 16, Loss: 0.7095834044141647
Epoch: 17, Loss: 0.7095834044141647
Epoch: 18, Loss: 0.7095834044141647
Epoch: 19, Loss: 0.7095834044141647
Epoch: 20, Loss: 0.7095834044141647
Epoch: 21, Loss: 0.7095834044141647
Epoch: 22, Loss: 0.7095834044141647
Epoch: 23, Loss: 0.7095834044141647
Epoch: 24, Loss: 0.7095834044141647
Epoch: 25, Loss: 0.7095834044141647


In [286]:
with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred = (y_pred > .5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"Accuracy: {(accuracy.item()) * 100}%")

Accuracy: 52.462297677993774%
