In [2]:
!pip list | grep torch

torch                                    2.4.0
torchvision                              0.19.0


In [3]:
import torch 

print(torch.__version__)

2.4.0


In [4]:
if torch.cuda.is_available():
    print(f"GPU:{torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available")

GPU is not available


In [6]:
##creating a tensor

# using empty 
a = torch.empty(2,3)

In [7]:
# check type 
type(a)

torch.Tensor

In [8]:
# using zeros 
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
#using rand
torch.rand(2,3) # random values

tensor([[0.4491, 0.2213, 0.7838],
        [0.1717, 0.6096, 0.5746]])

In [12]:
#using of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
torch.manual_seed(100)
torch.rand(2,3)
## same values everytime

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [18]:
torch.tensor([12,3]) #1D TENSOR

tensor([12,  3])

In [19]:
torch.tensor([[12,3], [4,5]]) #2D TENSOR 

tensor([[12,  3],
        [ 4,  5]])

In [20]:
torch.tensor([[1,2,3],[4,5,6],[7,8,9]]) #3D TENSOR

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [26]:
# other ways

#arange

print("arange ", torch.arange(10))

# using linspace 

print("linspace ", torch.linspace(0,20,7)) # linearly spaced

# using eye

print("eye", torch.eye(5,5))

#using full

print("full", torch.full((3,3), 89))

arange  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
linspace  tensor([ 0.0000,  3.3333,  6.6667, 10.0000, 13.3333, 16.6667, 20.0000])
eye tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
full tensor([[89, 89, 89],
        [89, 89, 89],
        [89, 89, 89]])


In [27]:
### tensor shapes


x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]])
x.shape

torch.Size([3, 3])

In [28]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [29]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [30]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [40]:
torch.rand_like(x, dtype=torch.float32) ## only generates float so this code doesnot work

tensor([[0.1033, 0.9702, 0.9481],
        [0.9787, 0.3268, 0.9200],
        [0.0503, 0.4583, 0.8608]])

In [34]:
## data types 


x.dtype

torch.int64

In [36]:
# assign data type 

y = torch.tensor([[1.0,2.0,3.0], [3.0,4.0,5.0]], dtype=torch.int32) # similar for float
y

tensor([[1, 2, 3],
        [3, 4, 5]], dtype=torch.int32)

In [38]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [41]:
### mathematical operations 

# scalar

x = torch.rand(2,2)
x

tensor([[0.4882, 0.7981],
        [0.2011, 0.1914]])

In [42]:
# add
x+2
## similarly we can do sub, mul, div, int div i.e. //, mod, power


tensor([[2.4882, 2.7981],
        [2.2011, 2.1914]])

In [43]:
a = torch.rand(2,3)
b = torch.rand(2,3)

In [44]:
a+b

tensor([[1.4477, 1.0211, 0.6410],
        [0.7730, 1.9828, 1.3718]])

In [45]:
a-b

tensor([[ 0.3481,  0.8871,  0.4074],
        [ 0.4282, -0.0052,  0.1230]])

In [46]:
a*b

tensor([[0.4937, 0.0639, 0.0612],
        [0.1035, 0.9828, 0.4666]])

In [47]:
a/b

tensor([[ 1.6332, 14.2372,  4.4884],
        [ 3.4843,  0.9948,  1.1970]])

In [48]:
a//b

tensor([[ 1., 14.,  4.],
        [ 3.,  0.,  1.]])

In [49]:
a**b

tensor([[0.9425, 0.9969, 0.9273],
        [0.9159, 0.9888, 0.8338]])

In [50]:
a%b

tensor([[0.3481, 0.0159, 0.0570],
        [0.0835, 0.9888, 0.1230]])

In [51]:
c = torch.tensor([1, -2, 3, -4])

torch.abs(c)

tensor([1, 2, 3, 4])

In [56]:
c = torch.tensor([1, 2,4, 5, 6,7])

In [57]:
torch.neg(c)

tensor([-1, -2, -4, -5, -6, -7])

In [58]:
torch.round(c)

tensor([1, 2, 4, 5, 6, 7])

In [59]:
torch.ceil(c)

tensor([1, 2, 4, 5, 6, 7])

In [60]:
torch.floor(c)

tensor([1, 2, 4, 5, 6, 7])

In [69]:
d = torch.randint(
    size=(2, 3),
    low=0,
    high=10,
    dtype=torch.float32,
)

In [63]:
d

tensor([[8, 8, 4],
        [2, 4, 1]])

In [64]:
torch.sum(d)

tensor(27)

In [66]:
torch.sum(d, dim=0)

tensor([10, 12,  5])

In [67]:
torch.sum(d, dim=1)

tensor([20,  7])

In [72]:
torch.mean(d), torch.mean(d, dim=0)

(tensor(8.5000), tensor([7.5000, 9.0000, 9.0000]))

In [71]:
torch.median(d)

tensor(9.)

In [73]:
torch.prod(d)

tensor(367416.)

In [74]:
torch.std(d)

tensor(0.8367)

In [75]:
torch.var(d)

tensor(0.7000)

In [76]:
torch.argmax(d)

tensor(1)

In [77]:
torch.argmin(d)

tensor(0)

In [79]:
a = torch.rand(2,3)
b = torch.rand(3,3)
torch.matmul(a, b)

tensor([[1.1337, 1.1318, 1.2645],
        [0.7755, 0.7986, 0.8281]])

In [80]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])
torch.dot(vector1, vector2)

tensor(11)

In [87]:
torch.transpose(torch.tensor([[1,2], [3,4]]), 0, 1)

tensor([[1, 3],
        [2, 4]])

In [ ]:
# torch.det()
# torch.inverse(

